import os
import sys
import glob
import json
import soundfile as sf
from indic_transliteration import sanscript

sys.path.insert(0, '/home/ubuntu/vagdhenu/src')
import prep_text as PT

# The exact 1:1 mapping of Chapter 1 slices to Gita text
# Verified by direct audio listening!
ch1_mapping = [
    (0, "धर्माक्षेत्रे कुरुक्षेत्रे समवेता युयुत्सवः", "dharma-kṣetre kuru-kṣetre samavetā yuyutsavaḥ", 1, 1),
    (1, "मामकाः पाण्डवाश्चैव किमकुर्वत सञ्जय", "māmakāḥ pāṇḍavāś caiva kim akurvata sañjaya", 1, 1),
    (2, "सञ्जय उवाच दृष्ट्वा तु पाण्डवानीकं", "sañjaya uvāca / dṛṣṭvā tu pāṇḍavānīkaṁ", 1, 2),
    (3, "व्यूढं दुर्योधनस्तदा", "vyūḍhaṁ duryodhanas tadā", 1, 2),
    (4, "आचार्यमुपसङ्गम्य राजा वचनमब्रवीत्", "ācāryam upasaṅgamya rājā vacanam abravīt", 1, 2),
    (5, "पश्यैतां पाण्डुपुत्राणामाचार्य महतीं चमूम्", "paśyaitāṁ pāṇḍu-putrāṇām ācārya mahatīṁ camūm", 1, 3),
    (6, "व्यूढां द्रुपदपुत्रेण तव शिष्येण धीमता", "vyūḍhāṁ drupada-putreṇa tava śiṣyeṇa dhīmatā", 1, 3),
    (7, "अत्र शूरा महेष्वासा भीमार्जुनसमा युधि", "atra śūrā maheṣv-āsā bhīmārjuna-samā yudhi", 1, 4),
    (8, "युयुधानो विराटश्च द्रुपदश्च महारथः", "yuyudhāno virāṭaś ca drupadaś ca mahā-rathaḥ", 1, 4),
    (9, "धृष्टकेतुश्चेकितानः काशिराजश्च वीर्यवान्", "dhṛṣṭaketuś cekitānaḥ kāśirājaś ca vīryavān", 1, 5),
    (10, "पुरुजित्कुन्तिभोजश्च शैब्यश्च नरपुङ्गवः", "purujit kuntibhojaś ca śaibyaś ca nara-puṅgavaḥ", 1, 5),
    (11, "युधामन्युश्च विक्रान्त उत्तमौजाश्च वीर्यवान्", "yudhāmanyuś ca vikrānta uttamaujāś ca vīryavān", 1, 6),
    (12, "सौभद्रो द्रौपदेयाश्च सर्व एव महारथाः", "saubhadro draupadeyāś ca sarva eva mahā-rathāḥ", 1, 6),
    (13, "अस्माकं तु विशिष्टा ये तान्निबोध द्विजोत्तम", "asmākaṁ tu viśiṣṭā ye tān nibodha dvijottama", 1, 7),
    (14, "नायका मम सैन्यस्य संज्ञार्थं तान्ब्रवीमि ते", "nāyakā mama sainyasya saṁjñārthaṁ tān bravīmi te", 1, 7),
    (15, "भवान्भीष्मश्च कर्णश्च कृपश्च समितिञ्जयः", "bhavān bhīṣmaś ca karṇaś ca kṛpaś ca samitiṁ-jayaḥ", 1, 8),
    (16, "अश्वत्थामा विकर्णश्च सौमदत्तिस्तथैव च", "aśvatthāmā vikarṇaś ca saumadattis tathaiva ca", 1, 8),
    (17, "अन्ये च बहवः शूरा मदर्थे त्यक्तजीविताः", "anye ca bahavaḥ śūrā mad-arthe tyakta-jīvitāḥ", 1, 9),
    (18, "नानाशास्त्रप्रहरणाः सर्वे युद्धविशारदाः", "nānā-śastra-praharaṇāḥ sarve yuddha-viśāradāḥ", 1, 9),
    (19, "अपर्याप्तं तदस्माकं बलं भीष्माभिरक्षितम्", "aparyāptaṁ tad asmākaṁ balaṁ bhīṣmābhirakṣitam", 1, 10),
    (20, "पर्याप्तं त्विदमेतेषां बलं भीमाभिरक्षितम्", "paryāptaṁ tv idam eteṣāṁ balaṁ bhīmābhirakṣitam", 1, 10),
    (21, "अयनेषु च सर्वेषु यथाभागमवस्थिताः", "ayaneṣu ca sarveṣu yathā-bhāgam avasthitāḥ", 1, 11),
    (22, "भीष्ममेवाभिरक्षन्तु भवन्तः सर्व एव हि", "bhīṣmam evābhirakṣantu bhavantaḥ sarva eva hi", 1, 11),
    (23, "तस्य सञ्जनयन्हर्षं कुरुवृद्धः पितामहः", "tasya sañjanayan harṣaṁ kuru-vṛddhaḥ pitāmahaḥ", 1, 12),
    (24, "सिंहनादं विनद्योच्चैः शङ्खं दध्मो प्रतापवान्", "siṁha-nādaṁ vinadyoccaiḥ śaṅkhaṁ dadhmau pratāpavān", 1, 12),
    (25, "ततः शङ्खाश्च भेर्यश्च पणवानकगोमुखाः", "tataḥ śaṅkhāś ca bheryaś ca paṇavānaka-gomukhāḥ", 1, 13),
    (26, "सहसैवाभ्यहन्यन्त स शब्दस्तुमुलोऽभवत्", "sahasaivābhyahanyanta sa śabdas tumulo 'bhavat", 1, 13),
    (27, "ततः श्वेतैर्हयैर्युक्ते महति स्यन्दने स्थितौ", "tataḥ śvetair hayair yukte mahati syandane sthitau", 1, 14),
    (28, "माधवः पाण्डवश्चैव दिव्यौ शङ्खौ प्रदध्मतुः", "mādhavaḥ pāṇḍavaś caiva divyau śaṅkhau pradadhmatuḥ", 1, 14),
    (29, "पाञ्चजन्यं हृषीकेशो देवदत्तं धनञ्जयः", "pāñcajanyaṁ hṛṣīkeśo devadattaṁ dhanañjayaḥ", 1, 15),
    (30, "पौण्ड्रं दध्मौ महाशङ्खं भीमकर्मा वृकोदरः", "pauṇḍraṁ dadhmau mahā-śaṅkhaṁ bhīma-karmā vṛkodaraḥ", 1, 15),
    (31, "अनन्तविजयं राजा कुन्तीपुत्रो युधिष्ठिरः", "anantavijayaṁ rājā kuntī-putro yudhiṣṭhiraḥ", 1, 16),
    (32, "नकुलः सहदेवश्च सुघोषमणिपुष्पकौ", "nakulaḥ sahadevaś ca sughoṣa-maṇipuṣpakau", 1, 16),
    (33, "काश्यश्च परमेष्वासः शिखण्डी च महारथः", "kāśyaś ca parameṣv-āsaḥ śikhaṇḍī ca mahā-rathaḥ", 1, 17),
    (34, "धृष्टद्युम्नो विराटश्च सात्यकिश्चापराजितः", "dhṛṣṭadyumno virāṭaś ca sātyakiś cāparājitaḥ", 1, 17),
    (35, "द्रुपदो द्रौपदेयाश्च सर्वशः पृथिवीपते", "drupado draupadeyāś ca sarvaśaḥ pṛthivī-pate", 1, 18),
    (36, "सौभद्रश्च महाबाहुः शङ्खान्दध्मुः पृथक्पृथक्", "saubhadraś ca mahā-bāhuḥ śaṅkhān dadhmuḥ pṛthak pṛthak", 1, 18),
    (37, "स घोषो धार्तराष्ट्राणां हृदयानि व्यदारयत्", "sa ghoṣo dhārtarāṣṭrāṇāṁ hṛdayāni vyadārayat", 1, 19),
    (38, "नभश्च पृथिवीं चैव तुमुलो व्यनुनादयन्", "nabhaś ca pṛthivīṁ caiva tumulo 'byanunādayan", 1, 19),
    (39, "अथ व्यवस्थितान्दृष्ट्वा धार्तराष्ट्रान्कपिध्वजः", "atha vyavasthitān dṛṣṭvā dhārtarāṣṭrān kapi-dhvajaḥ", 1, 20),
    (40, "प्रवृत्ते शस्त्रसम्पाते धनुरुद्यम्य पाण्डवः", "pravṛtte śastra-sampāte dhanur udyamya pāṇḍavaḥ", 1, 20),
    (41, "हृषीकेशं तदा वाक्यमिदमाह महीपते", "hṛṣīkeśaṁ tadā vākyam idam āha mahī-pate", 1, 21),
    (42, "सेनयोरुभयोर्मध्ये रथं स्थापय मेऽच्युत", "senayor ubhayor madhye rathaṁ sthāpaya me 'cyuta", 1, 21),
    (43, "यावदेतान्निरिक्षेऽहं योद्धुकामानवस्थितान्", "yāvad etān nirīkṣe 'haṁ yoddhu-kāmān avasthitān", 1, 22),
    (44, "कैर्मया सह योद्धव्यमस्मिन् रणसमुद्यमे", "kair mayā saha yoddhavyam asmin raṇa-samudyame", 1, 22),
    (45, "योत्स्यमानानवेक्षेऽहं य एतेऽत्र समागताः", "yotsyamānān avekṣe 'haṁ ya ete 'tra samāgatāḥ", 1, 23),
    (46, "धार्तराष्ट्रस्य दुर्बुद्धेर्युद्धे प्रियचिकीर्षवः", "dhārtarāṣṭrasya durbuddher yuddhe priya-cikīrṣavaḥ", 1, 23),
    (47, "सञ्जय उवाच एवमुक्तो हृषीकेशो गुडाकेशेन भारत", "sañjaya uvāca / evam ukto hṛṣīkeśo guḍākeśena bhārata", 1, 24),
    (48, "सेनयोरुभयोर्मध्ये स्थापयित्वा रथोत्तमम्", "senayor ubhayor madhye sthāpayitvā rathottamam", 1, 24),
    (49, "भीष्मद्रोणप्रमुखतः सर्वेशाम च महीक्षिताम्", "bhīṣma-droṇa-pramukhataḥ sarveṣāṁ ca mahīkṣitām", 1, 25),
    (50, "उवाच पार्थ पश्यैतान्समवेतान्कुरूनिति", "uvāca pārtha paśyaitān samavetān kurūn iti", 1, 25),
    (51, "तत्रापश्यत्स्थितान्पार्थः पितॄनथ पितामहान्", "tatrāpaśyat sthitān pārthaḥ pitṝn atha pitāmahān", 1, 26),
    (52, "आचार्यान्मातुलान्भ्रातॄन्पुत्रान्पौत्रान्सखींस्तथा", "ācāryān mātulān bhrātṝn putrān pautrān sakhīṁs tathā", 1, 26),
    (53, "श्वशुरान्सुहृदश्चैव सेनयोरुभयोरपि", "śvaśurān suhṛdaś caiva senayor ubhayor api", 1, 27),
    (54, "तान्समीक्ष्य स कौन्तेयः सर्वान्बन्धूनवस्थितान्", "tān samīkṣya sa kaunteyaḥ sarvān bandhūn avasthitān", 1, 27),
    (55, "कृपया परयाविष्टो विषीदन्निदमब्रवीत्", "kṛpayā parayāviṣṭo viṣīdann idam abravīt", 1, 28),
    (56, "अर्जुन उवाच दृष्ट्वेमं स्वजनं कृष्ण युयुत्सुं समुपस्थितम्", "arjuna uvāca / dṛṣṭvemaṁ svajanaṁ kṛṣṇa yuyutsuṁ samupasthitam", 1, 28),
    (57, "सीदन्ति मम गात्राणि मुखं च परिशुष्यति", "sīdanti mama gātrāṇi mukhaṁ ca pariśuṣyati", 1, 29),
    (58, "वेपथुश्च शरीरे मे रोमहर्षश्च जायते", "vepathuś ca śarīre me romaharṣaś ca jāyate", 1, 29),
    (59, "गाण्डीवं स्रंसते हस्तात्त्वक्चैव परिदह्यते", "gāṇḍīvaṁ sraṁsate hastāt tvak caiva paridahyate", 1, 30),
    (60, "न च शक्नोम्यवस्थातुं भ्रमतीव च मे मनः", "na ca śaknomy avasthātuṁ bhramatīva ca me manaḥ", 1, 30),
    (61, "निमित्तानि च पश्यामि विपरीतानि केशव", "nimittāni ca paśyāmi viparītāni keśava", 1, 31),
    (62, "न च श्रेयोऽनुपश्यामि हत्वा स्वजनमाहवे", "na ca śreyo 'nupaśyāmi hatvā svajanam āhave", 1, 31),
    (63, "न काङ्क्षे विजयं कृष्ण न च राज्यं सुखानि च", "na kāṅkṣe vijayaṁ kṛṣṇa na ca rājyaṁ sukhāni ca", 1, 32),
    (64, "किं नो राज्येन गोविन्द किं भोगैर्जीवितेन वा", "kiṁ no rājyena govinda kiṁ bhogair jīvitena vā", 1, 32),
    (65, "येषामर्थे काङ्क्षितं नो राज्यं भोगाः सुखानि च", "yeṣām arthe kāṅkṣitaṁ no rājyaṁ bhogāḥ sukhāni ca", 1, 33),
    (66, "त इमेऽवस्थिता युद्धे प्राणांस्त्यक्त्वा धनानि च", "ta ime 'vasthitā yuddhe prāṇāṁs tyaktvā dhanāni ca", 1, 33),
    (67, "आचार्याः पितरः पुत्रास्तथैव च पितामहाः", "ācāryāḥ pitaraḥ putrās tathaiva ca pitāmahāḥ", 1, 34),
    (68, "मातुलाः श्वशुराः पौत्राः श्यालाः सम्बन्धिनस्तथा", "mātulāḥ śvaśurāḥ pautrāḥ śyālāḥ sambandhinas tathā", 1, 34),
    (69, "एतान्न हन्तुमिच्छामि घ्नतोऽपि मधुसूदन", "etān na hantum icchāmi ghnato 'pi madhusūdana", 1, 35),
    (70, "अपि त्रैलोक्यराज्यस्य हेतोः किं नु महीकृते", "api trailokya-rājyasya hetoḥ kiṁ nu mahī-kṛte", 1, 35),
    (71, "निहत्य धार्तराष्ट्रान्नः का प्रीतिः स्याज्जनार्दन", "nihatya dhārtarāṣṭrān naḥ kā prītiḥ syāj janārdana", 1, 36),
    (72, "पापमेवाश्रयेदस्मान्हत्वैतानाततायिनः", "pāpam evāśrayed asmān hatvaitān ātatāyinaḥ", 1, 36),
    (73, "तस्मान्नार्हा वयं हन्तुं धार्तराष्ट्रान्सबान्धवान्", "tasmān nārhā vayaṁ hantuṁ dhārtarāṣṭrān sa-bāndhavān", 1, 37),
    (74, "स्वजनं हि कथं हत्वा सुखिनः स्याम माधव", "svajanaṁ hi kathaṁ hatvā sukhinaḥ syāma mādhava", 1, 37),
    (75, "यद्यप्येते न पश्यन्ति लोभोपहतचेतसः", "yady apy ete na paśyanti lobhopahata-cetasaḥ", 1, 38),
    (76, "कुलक्षयकृतं दोषं मित्रद्रोहे च पातकम्", "kula-kṣaya-kṛtaṁ doṣaṁ mitra-drohe ca pātakam", 1, 38),
    (77, "कथं न ज्ञेयमस्माभिः पापादस्मान्निवर्तितुम्", "kathaṁ na jñeyam asmābhiḥ pāpād asmān nivartitum", 1, 39),
    (78, "कुलक्षयकृतं दोषं प्रपश्यद्भिर्जनार्दन", "kula-kṣaya-kṛtaṁ doṣaṁ prapaśyadbhir janārdana", 1, 39),
    (79, "कुलक्षये प्रणश्यन्ति कुलधर्माः सनातनाः", "kula-kṣaye praṇaśyanti kula-dharmāḥ sanātanāḥ", 1, 40),
    (80, "धर्मे नष्टे कुलं कृत्स्नमधर्मोऽभिभवत्युत", "dharme naṣṭe kulaṁ kṛtsnam adharmo 'bhibhavaty uta", 1, 40),
    (81, "अधर्माभिभवात्कृष्ण प्रदुष्यन्ति कुलस्त्रियः", "adharmābhibhavāt kṛṣṇa praduṣyanti kula-striyaḥ", 1, 41),
    (82, "स्त्रीषु दुष्टासु वार्ष्णेय जायते वर्णसङ्करः", "strīṣu duṣṭāsu vārṣṇeya jāyate varṇa-saṅkaraḥ", 1, 41),
    (83, "सङ्करो नरकायैव कुलघ्नानां कुलस्य च", "saṅkaro narakāyaiva kula-ghnānāṁ kulasya ca", 1, 42),
    (84, "पतन्ति पितरो ह्येषां लुप्तपिण्डोदकक्रियाः", "patanti pitaro hy eṣāṁ lupta-piṇḍodaka-kriyāḥ", 1, 42),
    (85, "दोषैरेतैः कुलघ्नानां वर्णसङ्करकारकैः", "doṣair etaiḥ kula-ghnānāṁ varṇa-saṅkara-kārakaiḥ", 1, 43),
    (86, "उत्साद्यन्ते जातिधर्माः कुलधर्माश्च शाश्वताः", "utsādyante jāti-dharmāḥ kula-dharmāś ca śāśvatāḥ", 1, 43),
    (87, "उत्सन्नकुलधर्माणां मनुष्याणां जनार्दन", "utsanna-kula-dharmāṇāṁ manuṣyāṇāṁ janārdana", 1, 44),
    (88, "नरकेऽनियतं वासो भवतीत्यनुशुश्रुम", "narake 'niyataṁ vāso bhavatīty anuśuśruma", 1, 44),
    (89, "अहो बत महत्पापं कर्तुं व्यवसिता वयम्", "aho bata mahat pāpaṁ kartuṁ vyavasitā vayam", 1, 45),
    (90, "यद्राज्यसुखलोभेन हन्तुं स्वजनमुद्यताः", "yad rājya-sukha-lobhena hantuṁ svajanam udyatāḥ", 1, 45),
    (91, "यदि मामप्रतीकारमशस्त्रं शस्त्रपाणयः", "yadi mām apratīkāram aśastraṁ śastra-pāṇayaḥ", 1, 46),
    (92, "धार्तराष्ट्रा रणे हन्युस्तन्मे क्षेमतरं भवेत्", "dhārtarāṣṭrā raṇe hanyus tan me kṣemataraṁ bhavet", 1, 46),
    (93, "सञ्जय उवाच एवमुक्त्वार्जुनः सङ्ख्ये रथोपस्थ उपाविशत्", "sañjaya uvāca / evam uktvārjunaḥ saṅkhye rathopastha upāviśat", 1, 47),
    (94, "विसृज्य सशरं चापं शोकसंविग्नमानसः", "visṛjya sa-śaraṁ cāpaṁ śoka-saṁvigna-mānasaḥ", 1, 47),
]

print(f"Total mapped gold verses: {len(ch1_mapping)}")
